# A string used to differentiate different projects deployed to the same Hosted Region.
# Example: my-project-id
project_id = "10x-cards"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and functions in this schema will get API
# endpoints. public and storage are always part of the API, so you don't need to add them here.
schemas = ["public", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or function.
# Limits payload size for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. Must be a valid PostgreSQL version number.
major_version = 15

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323

# Email testing server. Emails sent with the local dev setup are not actually sent - they are monitered
# and can be viewed from the email testing server web interface.
[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:4321"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:4321"]
# How long tokens are valid, in seconds. Defaults to 3600 (1 hour), maximum 604,800 seconds (one week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user can be invited to the project via a link sent via email.
enable_confirmations = true
# If enabled, users will need to confirm their email address before signing in.
double_confirm_changes = true

# Uncomment to customize email template
# [auth.email.template.invite]
# subject = "You have been invited"
# body_path = "./supabase/templates/invite.html"

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = false
# If enabled, users will need to confirm their phone number before signing in.
enable_confirmations = false
# Template for sent OTP messages.
template = "Your code is {{ .Code }} ."

# Use pre-defined map of phone number to OTP for testing.
[auth.sms.test_otp]
# 4152127777 = "123456"

# This hook runs before a token is issued and allows you to add additional claims based on the authentication method used.
[auth.hook.custom_access_token]
enabled = false
uri = ""

# Configure one of the supported OAuth providers
[auth.external.apple]
enabled = false
client_id = ""
# DO NOT commit your OAuth provider secret to git. Use environment variables instead.
secret = ""
# Overrides the default auth redirect URL.
redirect_uri = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirect URL.
redirect_uri = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirect URL.
redirect_uri = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirect URL.
redirect_uri = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirect URL.
redirect_uri = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirect URL.
redirect_uri = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirect URL.
redirect_uri = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirect URL.
redirect_uri = ""

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirect URL.
redirect_uri = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirect URL.
redirect_uri = ""

[auth.external.notion]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirect URL.
redirect_uri = ""

[auth.external.slack]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirect URL.
redirect_uri = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirect URL.
redirect_uri = ""

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirect URL.
redirect_uri = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirect URL.
redirect_uri = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirect URL.
redirect_uri = ""

[analytics]
enabled = false
port = 54327
# Configure one of the supported backends: bigquery, snowflake, postgres, or segment.
backend = "postgres"

# Experimental features may be deprecated at any time
[experimental]
# Configures Postgres storage engine to use origintimestamp for timestamp columns.
# This setting affects new tables only. Existing tables will not be affected.
# origin_timestamp_utc_only = false

# Configures the amount of data sent to telemetry.
# telemetry_enabled = false

# Configure function settings

[realtime]
enabled = true
# max_connections = 1000
